### ISSUE TITLE
請問只支援iOS嗎？

### ISSUE THREAD

**Issue by ChaoTzuJung** [mengpeilee/react-native-fitbit#4]
請問運行Fitbit App時，是只能在iOS手機上運行嗎？

**Comment by mengpeilee** [comment]
@ChaoTzuJung Android也可以哦！ 只要有app的callback url都可以

**Comment by mengpeilee** [comment]
@ChaoTzuJung 
In Android, you need to set URL scheme for your app.
Please see this page: https://stackoverflow.com/questions/36244507/how-to-set-a-url-scheme-link-for-a-react-native-app

If you have any question, please feel free to ask me!
