### ISSUE TITLE
How to make it work on Android

### ISSUE THREAD

**Issue by linux-wizzard** [mengpeilee/react-native-fitbit#5]
Could you create **README** for android?
Thank you.

**Comment by mengpeilee** [comment]
@linux-wizzard Sure, I'll do it recently.
In Android, you need to set URL scheme for your app. 
Please see this page: https://stackoverflow.com/questions/36244507/how-to-set-a-url-scheme-link-for-a-react-native-app

If you have any question, please feel free to ask me!

**Comment by linux-wizzard** [comment]
Ok thank you. I have one question. Does it matter what callback do I put into manifest file. Can I put there some random string like this 'something://randomString' ?. Thank you.

**Comment by PujanShah22** [comment]
@mengpeilee , How should I get access-token of user after successfully login and get him back to app? I'm not getting anything for android with deep linking. It's only restarting app.

Can you share a code of example for this or any steps to get access-token after login?

**Comment by mengpeilee** [comment]
you can catch callback url

**Comment by sudhirkumarojhaa** [comment]
Have u got any work around @PujanShah22 ? 
I am able to fetch call back url, but can't get the access_token.

**Comment by mengpeilee** [comment]
@sudhirkumarojhaa Hi, access_token will be back on URL. Split it then you can get the token
